# Generated by Django 4.0.1 on 2022-01-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ótimo', 'Ótimo'), ('bom', 'Bom'), ('ruim', 'Ruim')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numticket', models.CharField(max_length=50, verbose_name='Número do Ticket')),
                ('assunt', models.CharField(max_length=50, verbose_name='Tema')),
                ('client', models.CharField(max_length=50, verbose_name='CLiente')),
                ('agent', models.CharField(max_length=50, verbose_name='Agente responsável')),
                ('dataresp', models.DateField(verbose_name='Data da Resposta')),
                ('conteudo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficios', models.CharField(max_length=50, verbose_name='Número do Ofício')),
                ('orgao', models.CharField(max_length=50, verbose_name='Órgão')),
                ('envio', models.DateField(verbose_name='Data do Envio')),
                ('temaofi', models.CharField(max_length=50, verbose_name='Tema do Ofício')),
                ('anexs', models.FileField(upload_to='anexooficio/')),
                ('questionamento', models.TextField(blank=True)),
                ('recebimento', models.DateField(verbose_name='Data do Recebimento')),
                ('conteudo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('profissao', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=8)),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('azul', 'Azul'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('prata', 'Prata'), ('vermelho', 'Vermelho')], max_length=20)),
                ('ano', models.IntegerField()),
                ('preco', models.FloatField()),
                ('foto_capa', models.ImageField(upload_to='images')),
                ('tipo', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro')], max_length=10)),
                ('acessorios', models.ManyToManyField(to='app.Acessorio')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proprietario')),
            ],
        ),
    ]
