# Generated by Django 4.0.1 on 2022-01-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficios',
            name='titulo_oficio',
            field=models.CharField(default='', max_length=50, verbose_name='Tema do Ofício'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oficios',
            name='conteudo',
            field=models.TextField(blank=True, verbose_name='Resposta do Ofício'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='orgao',
            field=models.CharField(choices=[('ANVISA', 'ANVISA'), ('IBAMA', 'IBAMA'), ('CONAMA', 'CONAMA'), ('ANM', 'ANM'), ('MAPA', 'MAPA'), ('MTE', 'MTE'), ('CBM', 'CBM')], max_length=50, verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='questionamento',
            field=models.TextField(blank=True, verbose_name='Questionamento'),
        ),
    ]
