# Generated by Django 4.0.1 on 2022-01-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_oficios_titulo_oficio_alter_oficios_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficios',
            name='status_oficio',
            field=models.CharField(blank=True, choices=[('Aguardando Retorno', 'Aguardando Retorno'), ('Retorno Recebido', 'Retorno Recebido')], max_length=50, verbose_name='Status do Ofício'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='anexs',
            field=models.FileField(blank=True, upload_to='anexooficio/'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='oficios',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número do Ofício'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='titulo_oficio',
            field=models.CharField(max_length=50, verbose_name='Título do Ofício'),
        ),
    ]
