# Generated by Django 4.0.1 on 2022-01-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_oficios_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficios',
            name='recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Recebimento'),
        ),
    ]
