# Generated by Django 4.0.1 on 2022-01-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_oficios_conteudo_alter_oficios_temaofi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficios',
            name='questionamento',
            field=models.TextField(verbose_name='Questionamento'),
        ),
    ]
