# Generated by Django 4.0.1 on 2022-01-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_consultoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultoria',
        ),
        migrations.AlterModelOptions(
            name='oficios',
            options={'verbose_name': 'Ofício'},
        ),
        migrations.AlterModelTable(
            name='oficios',
            table='oficios',
        ),
    ]
