# Generated by Django 4.0.1 on 2022-01-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_consultoria_alter_oficios_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temm', models.CharField(blank=True, max_length=50, verbose_name='Temaoff')),
            ],
        ),
        migrations.RemoveField(
            model_name='oficios',
            name='temaofi',
        ),
        migrations.AddField(
            model_name='oficios',
            name='temm',
            field=models.ManyToManyField(to='app.Temes'),
        ),
    ]
