# Generated by Django 4.0.1 on 2022-01-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_temes_remove_oficios_temaofi_oficios_temm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temes',
            options={'verbose_name': 'Tema'},
        ),
        migrations.AlterField(
            model_name='temes',
            name='temm',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tema'),
        ),
        migrations.AlterModelTable(
            name='temes',
            table='Temess',
        ),
    ]
