# Generated by Django 4.0.1 on 2022-01-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_temes_options_alter_temes_temm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficios',
            name='responsavel_envio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Responsável pelo Envio'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='anexs',
            field=models.FileField(blank=True, upload_to='anexooficio/', verbose_name='Anexo'),
        ),
    ]
