# Generated by Django 4.0.1 on 2022-01-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_oficios_responsavel_envio_alter_oficios_anexs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficios',
            name='responsavel_envio',
            field=models.CharField(max_length=50, verbose_name='Responsável pelo Envio'),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='status_oficio',
            field=models.CharField(choices=[('Aguardando Retorno', 'Aguardando Retorno'), ('Retorno Recebido', 'Retorno Recebido')], max_length=50, verbose_name='Status do Ofício'),
        ),
    ]
